kind: Service
apiVersion: v1
metadata:
  name: hbrain-spring-boot-service
spec:
  type: NodePort
  selector:
    app: hbrain-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30017
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hbrain-spring-boot-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hbrain-spring-boot
    spec:
      containers:
      - name: template-spring-boot-controller
        image: 10.10.150.149:5000/ruyi-ai/hbrain-spring-boot:20170712-024925
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"

      imagePullSecrets:
        - name: 10.10.150.149
